apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSettingBinding
metadata:
  name: hypershift-cis
  namespace: openshift-compliance
profiles:
- apiGroup: compliance.openshift.io/v1alpha1
  kind: TailoredProfile
  name: hypershift-cis-hcp-demo
settingsRef:
  apiGroup: compliance.openshift.io/v1alpha1
  kind: ScanSetting
  name: default
